AWSTemplateFormatVersion: 2010-09-09
Description: EC2 Create via CircleCI

Parameters: 
#-------------------------------------------------------------------
# Base Name
#-------------------------------------------------------------------
  Namebase:
    Description: base name for lecture13
    Type: String
    Default: "lecture13"

Resources:
#-------------------------------------------------------------------
# EC2 Instance,Key Pair, Elastic IP Address
#-------------------------------------------------------------------
#EC2
  EC2ForCI:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPairForCI
      DisableApiTermination: false
      ImageId: ami-0f89bdd365c3d966d  #Amazon Linux 2 AMI（HVM）、9月18日時点
      InstanceType: t2.micro
      Monitoring: true
      AvailabilityZone:  !Select
        - 1
        - Fn::GetAZs: !Ref "AWS::Region"
      SubnetId: !ImportValue PublicSubnet1aForCI
      SecurityGroupIds:
        - !ImportValue SecGroupEC2ForCI
      Tags:
        - Key: Name
          Value: !Sub "${Namebase}-ec2"

#Key Pair
  KeyPairForCI:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: EC2KeyPairForCI
      KeyType: rsa

#Elastic IP Address
  ElasticIPForCI:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: vpc

  ElasticIPAssociateForCI:
    Type: AWS::EC2::EIPAssociation
    Properties: 
      AllocationId: !GetAtt ElasticIPForCI.AllocationId
      InstanceId: !Ref EC2ForCI

Outputs:
#-------------------------------------------------------------------
# Outputs
#-------------------------------------------------------------------
#EC2
  EC2ForCI:
    Value: !Ref EC2ForCI
    Export: 
      Name: EC2ForCI
