version: 2.1

orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@4.1.2

jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml
  cfn-deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/assume_role_with_web_identity:
          role_arn: $AWS_OIDC_ROLE_ARN
      - run:
          name: run cfn-deploy
          command: 
            aws cloudformation deploy --template-file ./cloudformation/1_VPC_CI.yml --stack-name lecture13-VPC --no-fail-on-empty-changeset --region ap-northeast-1
workflows:
  raisetech:
    jobs:
      - cfn-lint
      - cfn-deploy      
