AWSTemplateFormatVersion: 2010-09-09
Description: ALB Create

Parameters: 
#-------------------------------------------------------------------
# Base Name
#-------------------------------------------------------------------
  Namebase:
    Description: base name for lecture10
    Type: String
    Default: "lecture10"

Resources: 
#-------------------------------------------------------------------
# ALB
#-------------------------------------------------------------------
#ALB
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      Name: !Sub "${Namebase}-alb"
      Type: application
      Scheme: internet-facing
      SecurityGroups: 
        - !ImportValue SecGroupALB
      Subnets:
        - !ImportValue PublicSubnet1a
        - !ImportValue PublicSubnet1c
      Tags:
        - Key: Name
          Value: !Sub "${Namebase}-alb"
      
#ALB Listener
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      DefaultActions: 
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
      Port: 80
      Protocol: HTTP

#ALB Target Group
  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      Name: !Sub "${Namebase}-alb-tgp"
      VpcId: !ImportValue VPC
      TargetType: instance
      Targets: 
        - Id: !ImportValue EC2
      Port: 80
      Protocol: HTTP
      ProtocolVersion: HTTP1
      HealthCheckEnabled: yes
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /404.html
      HealthCheckPort: 80
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Tags: 
        - Key: Name
          Value: !Sub "${Namebase}-alb-tgp"
