AWSTemplateFormatVersion: 2010-09-09
Description: EC2 Create

Parameters: 
#-------------------------------------------------------------------
# Base Name
#-------------------------------------------------------------------
  Namebase:
    Description: base name for lecture10
    Type: String
    Default: "lecture10"

Resources:
#-------------------------------------------------------------------
# EC2 Instance,Key Pair, Elastic IP Address
#-------------------------------------------------------------------
#EC2
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPair
      DisableApiTermination: false
      ImageId: ami-0f89bdd365c3d966d  #Amazon Linux 2 AMI（HVM）、9月18日時点
      InstanceType: t2.micro
      Monitoring: true
      AvailabilityZone: ap-northeast-1a
      SubnetId: !ImportValue PublicSubnet1a
      SecurityGroupIds:
        - !ImportValue SecGroupEC2
      Tags:
        - Key: Name
          Value: !Sub "${Namebase}-ec2"

#Key Pair
  KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: EC2KeyPair
      KeyType: rsa

#Elastic IP Address
  ElasticIP:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: vpc

  ElasticIPAssociate:
    Type: AWS::EC2::EIPAssociation
    Properties: 
      AllocationId: !GetAtt ElasticIP.AllocationId
      InstanceId: !Ref EC2

Outputs:
#-------------------------------------------------------------------
# Outputs
#-------------------------------------------------------------------
#EC2
  EC2:
    Value: !Ref EC2
    Export: 
      Name: EC2