AWSTemplateFormatVersion: 2010-09-09
Description: S3 Create

Parameters: 
#-------------------------------------------------------------------
# Base Name
#-------------------------------------------------------------------
  Namebase:
    Description: base name for lecture10
    Type: String
    Default: "lecture10"

Resources: 
#-------------------------------------------------------------------
# S3
#-------------------------------------------------------------------
#S3 Bucket
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Sub "${Namebase}-anna-s3bucket"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: true
        IgnorePublicAcls: false
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub "${Namebase}-s3bucket"

#S3 Policy
  S3Policy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:*'
            Effect: Allow
            Resource: 
              - !Sub 'arn:aws:s3:::${S3Bucket}/*'
            Principal: 
              AWS: 
                - arn:aws:iam::442663203070:user/user